CREATE TABLE MEETINGDAYS(
	MD_courseNum VARCHAR(255) NOT NULL,
	MD_secNum VARCHAR(255) NOT NULL,
	MD_meetingDays VARCHAR(255) NOT NULL,
	PRIMARY KEY (MD_secNum, MD_courseNum, MD_meetingDays)
CONSTRAINT FK_MD_courseNum 
FOREIGN KEY (MD_courseNum)
REFERENCES COURSE(course_CourseNo),
CONSTRAINT FK_MD_secNum
FOREIGN KEY(MD_secNum)
REFERENCES SECTION (sec_secNum));

CREATE TABLE PREREQCOURSES(
	PR_CourseNo VARCHAR (225) NOT NULL,
	PR_prereqCourse VARCHAR(255) NOT NULL,
	PRIMARY KEY(PR_courseNo, PR_prereqCourse)
CONSTRAINT FK_PR_courseNo
FOREIGN KEY(PR_courseNo)
REFERENCES COURSE(course_CourseNo));

CREATE TABLE COLLEGEDEGREE(
	CD_Degree VARCHAR (225) NOT NULL,
	CD_profSSN INT(11) NOT NULL,
	PRIMARY KEY(CD_profSSN,CD_Degree)
CONSTRAINT FK_CD_profSSN
FOREIGN KEY (CD_profSSN)
REFERENCES PROFESSORS(prof_SSN));

CREATE TABLE ENROLLMENTRECORD (  
ER_secNum VARCHAR(255) NOT NULL,   
ER_studCWID INT(9) NOT NULL,   
ER_Grade VARCHAR(255) NOT NULL,   
ER_courseNum VARCHAR(255) NOT NULL,   
PRIMARY KEY (ER_secNum,ER_courseNum,ER_studCWID), 
CONSTRAINT FK_ER_coNum 
FOREIGN KEY (ER_secNum, ER_courseNum) 
REFERENCES SECTION(sec_secNum,sec_courseNo), 
CONSTRAINT FK_ER_studCWID 
FOREIGN KEY (ER_studCWID) 
REFERENCES STUDENTRECORDS (SR_CWID));

CREATE TABLE STUDENTRECORDS(
	SR_major_deptNo INT(11) NOT NULL,
	SR_CWID INT(9) NOT NULL,
	SR_Address VARCHAR(225) NOT NULL,
	SR_telephoneNo VARCHAR(225) NOT NULL,
	SR_firstName VARCHAR(225) NOT NULL,
	SR_lastName VARCHAR(225) NOT NULL,
PRIMARY KEY(SR_CWID)
CONSTRAINT STUDENTRECORDS_ibfk_1
FOREIGN KEY (SR_major_deptNo)
REFERENCES DEPARTMENT(dept_DeptNo);

CREATE TABLE SECTION(
	sec_profSSN INT(11) NOT NULL,
	sec_courseNo VARCHAR(255) NOT NULL,
	sec_secNum VARCHAR(255) NOT NULL,
	sec_Classroom VARCHAR(255) NOT NULL,
	sec_seatNo VARCHAR(255) NOT NULL,
	sec_beginTime VARCHAR(255) NOT NULL, 
	sec_endTime VARCHAR(255) NOT NULL,
PRIMARY KEY(sec_secNum, sec_courseNo)
CONSTRAINT FK_sec_profSSN
FOREIGN KEY(sec_profSSN)
REFERENCES PROFESSORS(prof_SSN);

CREATE TABLE COURSE(
	course_CourseNo VARCHAR(255) NOT NULL,
	course_Title VARCHAR(255) NOT NULL,
	course_Textbook VARCHAR(255),
	course_Units INT(11)NOT NULL,
PRIMARY KEY (course_CourseNo));

CREATE TABLE DEPARTMENT(
	dept_DeptNo INT(11) NOT NULL,
	dept_Name VARCHAR(255) NOT NULL,
	dept_OfficeLocation VARCHAR(255) NOT NULL,
	dept_Telephone VARCHAR(255) NOT NULL,
	PRIMARY KEY(dept_DeptNo));

CREATE TABLE PROFESSORS(
	prof_SSN INT(11) NOT NULL,
	prof_Sex VARCHAR(255) NOT NULL,
	prof_Name VARCHAR(255) NOT NULL,
	prof_City VARCHAR(255) NOT NULL,
	prof_Zipcode VARCHAR(255) NOT NULL,
	prof_st_Addr VARCHAR(255) NOT NULL,
	prof_State VARCHAR(255) NOT NULL,
	prof_Areacode VARCHAR(255) NOT NULL,
	prof_Seven_digit INT(7) NOT NULL,
	prof_Title VARCHAR(255) NOT NULL,
	prof_Salary VARCHAR(255) NOT NULL,
	PRIMARY KEY(prof_SSN));
